
import "../globals.css";

import CssBaseline from "@mui/material/CssBaseline";


export const metadata = {
  title: "listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <div >
       
        </div>
        <main>{children}</main>
      
      </body>
    </html>
  );
}
