import localFont from "next/font/local";
import "../globals.css";
import Footer from "@/components/footer/Footer.jsx";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import Navbar from "../(home)/_components/nav/Navbar";

export const metadata = {
  title: "listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <div className="px-[30px]">
       
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
