import localFont from "next/font/local";
import "../globals.css";
import Footer from "@/components/footer/Footer.jsx";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider, createTheme } from "@mui/material/styles";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <CssBaseline />
        <main>{children}</main>
        <div className="block">
          <Footer />
        </div>
      </body>
    </html>
  );
}
